soal no 1

In [33]:
import numpy as np

In [34]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[20, 3, 7], [16, 6, 7]])
X

array([[20,  3,  7],
       [16,  6,  7]])

In [35]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [36]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0]

array([20,  3,  7])

In [37]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1]

array([16,  6,  7])

soal no 2

In [38]:
import torch
import tensorflow

In [39]:
# ulangi soal nomor 1 menggunakan pytorch
X_pt = torch.tensor([[20, 3, 7], [16, 6, 7]])
X_pt

tensor([[20,  3,  7],
        [16,  6,  7]])

In [40]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [41]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0]

array([20,  3,  7])

In [42]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1]

array([16,  6,  7])

In [46]:
# ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.Variable([[20, 3, 7], [16, 6, 7]])
X_tf

NameError: name 'tf' is not defined