soal no 1

In [17]:
import numpy as np

In [18]:
# buat vector x dengan ukuran 3x1
x = np.array([20, 3, 7])
x

array([20,  3,  7])

In [19]:
# hitung nilai L2 norm dari vector x
(20**2 + 3**2 + 7**2)**(1/2)

21.400934559032695

soal no 2

In [20]:
# buat vector v dengan elemen (3,4)
v = np.array([[20, 3, 7, 6], [17, 6, 7, 3], [13, 10, 5, 4]])
v

array([[20,  3,  7,  6],
       [17,  6,  7,  3],
       [13, 10,  5,  4]])

In [21]:
# hitung nilai L2 norm dari vector v
(20**2 + 3**2 + 7**2 + 6**2)**(1/2)
(17**2 + 6**2 + 7**2 + 3**2)**(1/2)
(13**2 + 10**2 + 5**2 + 4**2)**(1/2)

17.60681686165901

In [32]:
# tampilkan unit vector dari vector v
v = np.array([[20, 3, 7, 6], [17, 6, 7, 3], [13, 10, 5, 4]])
print("Unit vector:", v )

Unit vector: [[20  3  7  6]
 [17  6  7  3]
 [13 10  5  4]]


In [31]:
# hitung panjang unit vector dari vector v
v = np.array([[20, 3, 7, 6], [17, 6, 7, 3], [13, 10, 5, 4]])
print("Panjang vektor:", np.linalg.norm(v))

Panjang vektor: 34.45286635390443
