Soal no 1


In [5]:
import numpy as np

In [6]:
# buat vector x dengan ukuran 3x1
x = np.array([20, 3, 7])
x

array([20,  3,  7])

In [7]:
# hitung panjang vector x
len(x)

3

In [8]:
# tampilkan ukuran vector x
x.shape

(3,)

In [9]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [10]:
# akses elemen pertama dari vector x
x[0]

np.int64(20)

In [11]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

soal no 2

In [12]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([20,  3,  7])

In [13]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [18]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[17, 6, 7]])
y

y_t = y.T
y_t

array([[17],
       [ 6],
       [ 7]])

In [15]:
# tampilkan ukuran dari vector y_t
y_t.shape

(3,)

soal no 3

In [19]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [20]:
x_pt = torch.tensor([20, 3, 7])
x_pt

tensor([20,  3,  7])

In [21]:
x_tf = tf.Variable([20, 3, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20,  3,  7], dtype=int32)>